GET http://localhost:4000/test
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjczY3VEelV4RjRIb3RDX1dRWEZzcyJ9.eyJpc3MiOiJodHRwczovL2Rldi1tczczb21iai51cy5hdXRoMC5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDkwODYyODQ2OTA2Nzc5Mzk5NjUiLCJhdWQiOlsiaWduaXRlLXJlbmF0b2RhbHRpYmEtbGFiMDEtYXV0aCIsImh0dHBzOi8vZGV2LW1zNzNvbWJqLnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NDkwODI1NzcsImV4cCI6MTY0OTE2ODk3NywiYXpwIjoicXlPdDR6d1Q3WWVwTTRUTzhCUVpWc3AwYzBUaW1tMVUiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIn0.RutUT1ErmfHxzYdYC-VSHHx7rLuK46HCY0rjxu5jZyK0CCvSfOCgUbGX-dswGVmhYLdhmMDLf7RPWNFOTbMjeVCixPqqml2QLo_WUtiUNoxfep_uZui3xuo2rREtClS00kUPyp7lpylUzWqSFoJlJjzsb6r7jkb6QVk7kXf-O0wJnbOI3WRLlTNksEPzOOBf6rErpI0g2C9BaMdBRtz_e-l34MKhzMABkOXhATJVYV5pj38-Thfw5ePAfkBqeeCEalU8mCsIHXJo32EUWD1EmQsan3xZvjcI8pZ5BYE7mzqk154_iXIrCyqLjgkaj0hcubK4XzWnQmpnd1i0vsn8mA